### PR TITLE
FIX run with Docker environment / problem with IP address of agent

### PR DESCRIPTION
**Pull request by xaviernopre**
- Use local IP address for agent endpoints
- Add output in terminal to print endpoint (usefull for scenario)
- Add Makefile to simplify commands
- Update README with simplified commands and more informations

### CODE REVIEW

**Comment by TelegramSam** [comment]
This fix helps the docker scenario but at the expense of non-private network scenarios. We need a way to have the browser use the same network as the agents use to talk to each other.

**Comment by TelegramSam** [comment]
Now that I've had a look through the problem... the code should work in Docker, as long as you don't use localhost or 127.0.0.1 in the browser for the ip. Were you using your own local machine ip?

**Comment by xaviernopre** [comment]
@TelegramSam There were a mistake for the URL to use to access each agent. I have tried under MacOS and Linux : the URL to use is http://localhost:8094 (or 8095). I have remodeled the README, to be more Markdown compliant, and to be more simplier, for each environment (Linux and MacOS). Can you check it and give me feedbacks ? ;-)

Why do you need a way to have the browser use the same network as the agents use to talk to each other ? In my case (Docker under MacOS), there is no choice : I have to open browser tabs with `localhost` and processes have to communicate with internal docker IP addresses (`172.17.0.3` for example). For this reason, I have added this output in each agent console : `Agent Offer Endpoint : "http://172.17.0.2:8094/offer"`. And in the README, I have explained to get this URL to use the demo (i.e. send connection request). I think all is OK like this, no ?

**Comment by dbluhm** [comment]
@xaviernopre I think the Makefile you've added is great but having it be a Makefile could introduce some confusion as the Makefile doesn't build the code but rather does docker operations. It's not as simple but I think having a shell script named "docker-setup.sh" that performs the operations in your Makefile would be a clearer solution. Or, perhaps, clearly labeling the Makefile by changing "build" to "docker-build" and "start" to "docker-start" could help avoid the same confusion.

**Comment by xaviernopre** [comment]
@dbluhm You're right, "build" and "start" can be confusing, I have pushed changes adding "docker-" prefix for each target in the Makefile

**Comment by TelegramSam** [comment]
> Why do you need a way to have the browser use the same network as the agents use to talk to each other ?

I think we need this because it mimics the way Agents will generally work in the real world. Agents will generally not use a private network (like Docker provides) to communicate, and I worry that optimizing for this private network case will cause negative side effects within the codebase.

**Comment by xaviernopre** [comment]
@dbluhm @TelegramSam I have pushed fixes in README for commands

**Comment by swcurran** [comment]
This sounds like the same issue we ran into. The solution in that case was
to have 2 different environment variables, one each for the app and the
API. That works if those addresses are the same or different - it becomes a
config injection concern.

**Comment by xaviernopre** [comment]
> I think we need this because it mimics the way Agents will generally work in the real world. Agents will generally not use a private network (like Docker provides) to communicate, and I worry that optimizing for this private network case will cause negative side effects within the codebase.

Perhaps there can be some little side effects, but it is very useful to be able to checkout the repo, and quickly and simply be able to run the demo ! Docker is very useful to avoid install of many softwares or libs, and in my opinion (and my knowledges), my configuration is the only that can run correctly. And in addition, I'm under MacOS, so the README instructions for Linux are not usable... ;-) . And I think that developpers (and users of this demo) can understand the limits and extrapolate for the real life ;-)

**Comment by swcurran** [comment]
Amen!

**Comment by xaviernopre** [comment]
@TelegramSam I'm back (after some days off), finally, is it OK for you ?

**Comment by xaviernopre** [comment]
@TelegramSam Hi :-) . I will be soon ready to do a new PR with "dockerization" for `vcx/wrappers/python3/demo`, but for this, I need the current PR. Is it possible to merge it ? Thanks

**Comment by blhagadorn** [comment]
@xaviernopre Very nice! Possibly could you fork your own PR here in the meantime until this is approved, specifically just the makefile and your use of docker IP commands.  As @dbluhm mentioned regarding the use of a Makefile, it's possible to do what von-network has done, a series of scripts: https://github.com/bcgov/von-network/tree/master/scripts? 

One option regarding the concerns about creating a private network, since this is a reference agent (maybe we should define if we want to learn from a reference agent and get it going quick, like @swcurran would suggest, or if your changes should be a suggested feature for learning quickly but not apart of the official documentation?).  Regardless, for projects like https://github.com/kdenhartog/indy-dev we found that a Makefile and docker commands like yours do were really helpful for your stated preference of
> very useful to be able to checkout the repo, and quickly and simply be able to run the demo

**Comment by xaviernopre** [comment]
@blhagadorn I'm not sure to good understand your comments, and don't really understand what you're waiting from me, but I will try to answer... ;-) 

> @xaviernopre Very nice! Possibly could you fork your own PR here in the meantime until this is approved, specifically just the makefile and your use of docker IP commands. 

Sorry, I don't understand. Which PR are you talking about ? What do you want me to do ? 

> As @dbluhm mentioned regarding the use of a Makefile, it's possible to do what von-network has done, a series of scripts: https://github.com/bcgov/von-network/tree/master/scripts?

In my opinion, using a Makefile is very useful, simple and standard. And it is a (re)emerging standard. For example, https://github.com/bcgov/von-network/blob/master/manage do the same but without being a standard. If you want to know available commands, you have juste to take a look at the targets in the Makefile. Conversely, with `manage`(above), you have to read many code to extract available commands. And obviously, I have all documented in the README file.

> One option regarding the concerns about creating a private network, since this is a reference agent (maybe we should define if we want to learn from a reference agent and get it going quick, like @swcurran would suggest, or if your changes should be a suggested feature for learning quickly but not apart of the official documentation?).

My approach is the following : I list what I'm missing trying to use a lib or trying to run a sample code. For example, following this way, I have contributed with this https://github.com/hyperledger/indy-sdk/tree/master/docs/how-tos/write-did-and-query-verkey/nodejs, https://github.com/hyperledger/indy-sdk/blob/master/samples/nodejs/src/anoncredsRevocationScenario.js, ... It is the same here, this repo is a "reference implementation", that can be run, and the only/better solution for me (and other future ;-) ) on MacOs, is Docker :-) . As I said, developers are able to understand that this is a reference implementation, with some adjustments for the run.

> Regardless, for projects like the Indy-SDK learning and getting started guide https://github.com/kdenhartog/indy-dev we found that a Makefile and docker commands like yours do were really helpful for your stated preference of

Sorry, I don't understand what you mean...

**Comment by xaviernopre** [comment]
I have resolved conflicts. Is it possible to merge this PR ? ;-)

**Comment by xaviernopre** [comment]
@TelegramSam @dbluhm @swcurran @blhagadorn Why not merge this PR ? I have done this work and effort to help further developpers. I have answered your questions. Is there still a problem ? Thanks

**Comment by dbluhm** [comment]
@xaviernopre Sorry to take so long on this. I am testing out your changes now and will approve once everything checks out. Thanks for your patience!

**Comment by dbluhm** [comment]
@xaviernopre I submitted a PR against your branch with some minor clarifications and additions. Once you review that, I think this PR is just about ready to go.

**Comment by xaviernopre** [comment]
@dbluhm Great ! 😀

**Pull request merged**
