### PR TITLE
Route by message family

### PR DESCRIPTION
**Pull request by dbluhm**
This change will help with routing by message family and overall cleanliness of the code.

Functions that are message handlers now only take self and Message as arguments.

This will conflict with @ken-ebert's pull request; I can resolve these after his is merged.

### CODE REVIEW

**Comment by dbluhm** [comment]
Resolved conflicts between this and Ken's PR.

**Comment by TelegramSam** [comment]
This looks good, but I think taking one more step would help the organization quite a bit.

Message handlers are still registered individually, like this:

`await msg_router.register(CONN.SEND_REQUEST, connection.request_received)`

It would be nice to register a module by message family, and allow each module to route messages to the appropriate handler.

This does add a small layer of complexity to routing, but better encapsulates message families within the module, and it prevents the main router from being burdened with each message type. This will be important is the number of supported message families grows.

**Comment by dbluhm** [comment]
I was going for a more incremental approach but I'll update this PR with more commits to get to routing by message family.

**Comment by dbluhm** [comment]
Implemented routing by message family. This meant I had to introduce a new message family for messages intended to be consumed by the connections module sent from the UI. I called this family `connections_ui`.

**Comment by TelegramSam** [comment]
This is a great refactor. Tested and code reviewed.

**Pull request merged**
