### PR TITLE
LSI-16: remove GPL code

### PR DESCRIPTION
**Pull request by ryjones**
The second commit will mark this repo as read-only.

### CODE REVIEW

**Review by dhh1128 — COMMENTED** [review]
Removing GPL code is highly desirable. However, this particular repo is not central to the Indy ecosystem, and its maintainer is @TelegramSam , I think. I'd like him to weigh in on what the correct approach ought to be. (Removing this code breaks a feature, I think, but I'm not sure how important the feature is. It may be simpler to just retire the repo.)

**Comment by ryjones** [comment]
Could we do both? I'm operating under guidance from @swinslow

**Comment by dhh1128** [comment]
That would be fine with me. However, we should probably update its README.md to explain that it was archived, and to note that despite its Apache 2 LICENSE, it contains an artifact that uses a GPL license; it is therefore not usable as Apache 2 source if it is ever copied out of the archive.

**Comment by ryjones** [comment]
Does this look OK? https://github.com/hyperledger/indy-agent/blob/9de6cdc8c7f8cd00f8bf2d5cc1c9fcdb950f9df4/README.md

**Comment by dhh1128** [comment]
Yep. That looks good to me. I'm happy to merge this if I can get @TelegramSam to buy off.

**Comment by ryjones** [comment]
See also: https://jira.hyperledger.org/browse/LSI-20

**Review by TelegramSam — APPROVED** [review]
thanks for helping clean this up.

**Pull request merged**
